version: '3'
services:
    db:
        image: postgres:14-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: testtest
            POSTGRES_DB: test
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
            interval: 1s
            retries: 3
    app:
        image: spring-native-app:0.12.1
        container_name: native_app
        ports:
            - 8080:8080
        depends_on:
            db:
                condition: service_healthy
        
